"""Add example column to words

Revision ID: be73cae5163f
Revises: 
Create Date: 2024-07-13 19:46:41.661708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be73cae5163f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('example', sa.String(), nullable=True))
    op.add_column('words', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'date_added')
    op.drop_column('words', 'example')
    # ### end Alembic commands ###
